pipeline {
    agent { docker { image 'maven:3.6.3' } }
    stages {
        stage('build') {
            steps {
                cd consumerBanking
                sh 'mvn clean install'
            }
        }
    }
}
