name: hello-world
on: 
  pull_request:
    branches:    
      - master
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: | 
          echo "Hello World! Else Test"
          echo "${{ github.event }}"
